version: '3.8'

services:
  translations_editor:
    restart: always
    build:
      context: tools/internationalisation/editor
      args:
        LANG_PATH: '/app/lang'
        TRANSLATION_TYPES_PATH: '/app/translations.d.ts'
    ports:
      - "8000:8000"
    volumes:
      - ${LANG_PATH}:/app/lang
      - ${TRANSLATION_TYPES_PATH}:/app/translations.d.ts