// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_translations from "./routes/api/translations.ts";
import * as $index from "./routes/index.tsx";
import * as $FreshLogo from "./islands/FreshLogo.tsx";
import * as $SidebarLayout from "./islands/SidebarLayout.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/translations.ts": $api_translations,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/FreshLogo.tsx": $FreshLogo,
    "./islands/SidebarLayout.tsx": $SidebarLayout,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
